config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'category#select'
  get '/categories/:category_id', to: 'articles#articles_index', as: 'category_articles'
  get '/categories/:category_id/articles/:article_id', to: 'articles#show', as: 'article_description'
  get '/users/:user_id/products', to: 'products#user_products_index', as: 'user_products'
  get '/users/:user_id/products/user_data_registry', to: 'products#user_data_registry', as: 'user_data_registry'
  get '/categories/:category_id/articles/:article_id/users/:user_id/products/:product_id/parts/colour_personalization', to: 'articles#colour_personalization', as: 'article_color_personalization'
  post'/material_parts', to: 'material_parts#create'
  # get '/articles/new', to: 'articles#create', as: 'new_article'
  resources :articles, only: [:index, :new, :create, :update, :destroy]
  resources :category
  resources :manufacturer
  resources :products do
    resources :category
    resources :manufacturer
  end
  resources :users do
    resources :products
  end


end

app/models/category.rb
#:nodoc:
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/category_controller.rb
#:nodoc:
class CategoryController < ApplicationController
  def index
    @categories = Category.all
    flash[:error] = 'No references registered.' if @categories.empty?
  end

  def new
    @category = Category.new
  end

  def select
    
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category registered successfully.'
      redirect_to category_index_path
    else
      flash[:error] = @category.errors.full_messages.join(',')
      render 'new'
    end
  end

  def category_params
    params.require(:category).permit(:category_name, :description,
                                     :image, :dimension)
  end
  private :category_params
end

app/views/category/index.html.erb
<h4>Mis referencias</h4>

<table class="table">
  <thead>
    <th>Id</th>
    <th>Referencia</th>
    <th>Imagen</th>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.category_name %></td>
        <td><%= category.image %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Inicio", root_path %>

app/views/category/new.html.erb
<div class="row" >
  <div class="col-md-3"></div>
  <div class="col-md-6"> <h3> New Category </h3> </div>
  <div class="col-md-3"></div>
</div>

<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for @category, url: {action: 'create'} do |form|%>
      <div class="row">
        <div class="col-md-6"> <%= form.label :category_name, for:'category_name'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= form.text_field :category_name, class:'form-control' %> </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6"> <%= form.label :image, for:'image'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= form.text_field :image, class:'form-control' %> </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit "Register Category", class: 'btn btn-success'%>
        <%= link_to "Cancel", category_index_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

<%= link_to "Inicio", root_path %>

app/views/category/select.html.erb
<!-- /.container -->
    <div class="container">
      <div id="owl-demo" class="owlCarousel owl-theme">
          <div class="item"><%=image_tag("fullimage1.jpg", alt: "Example Image", class: "item-img")%></div>
        <div class="item"><%=image_tag("fullimage2.jpg", alt: "Example Image", class: "item-img")%></div>
        <div class="item"><%=image_tag("fullimage3.jpg", alt: "Example Image", class: "item-img")%></div>
      </div>
    </div>
<section class="products col-lg-12">
    <div class="container">
      <div class="products-item col-lg-4 col-md-6 col-s-12">
        <a href="#" class="products-item--link">
          <%= link_to category_articles_path(1), class: 'products-item--link' do %>
             <%= image_tag "bags.jpg", class: "products-item--img" %>
          <% end %>
          <div class="products-item--title">
          <%= link_to  "Bag", category_articles_path(1), class: 'products-item--link' %></div>
        </a>
      </div>
      <div class="products-item col-lg-4 col-md-6 col-s-12">
        <a href="#" class="products-item--link">
          <%= link_to category_articles_path(2), class: 'products-item--link' do %>
             <%= image_tag "scarfs.jpg", class: "products-item--img" %>
          <% end %>
          <div class="products-item--title"><%= link_to  "Scarf", category_articles_path(2), class: 'products-item--link' %></div>
        </a>
      </div>
      <div class="products-item col-lg-4 col-md-6 col-s-12">
        <a href="#" class="products-item--link">
          <%= link_to category_articles_path(3), class: 'products-item--link' do %>
             <%= image_tag "carpets.jpg", class: "products-item--img" %>
          <% end %>
          <div class="products-item--title"><%= link_to  "Carpet", category_articles_path(3), class: 'products-item--link' %></div>
        </a>
      </div>
    </div>
</section>