config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'category#select'
  get '/categories/:category_id', to: 'articles#articles_index', as: 'category_articles'
  get '/categories/:category_id/articles/:article_id', to: 'articles#show', as: 'article_description'
  get '/users/:user_id/products', to: 'products#user_products_index', as: 'user_products'
  get '/users/:user_id/products/user_data_registry', to: 'products#user_data_registry', as: 'user_data_registry'
  get '/categories/:category_id/articles/:article_id/users/:user_id/products/:product_id/parts/colour_personalization', to: 'articles#colour_personalization', as: 'article_color_personalization'
  post'/material_parts', to: 'material_parts#create'
  # get '/articles/new', to: 'articles#create', as: 'new_article'
  resources :articles, only: [:index, :new, :create, :update, :destroy]
  resources :category
  resources :manufacturer
  resources :products do
    resources :category
    resources :manufacturer
  end
  resources :users do
    resources :products
  end


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  belongs_to :product
  has_many :products, through: :category
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_items
  before_action :set_item, only: [:colour_personalization]
  before_action :set_product, only: [:colour_personalization]

  def articles_index
  end

  def index
    @articles = Article.all
    flash[:error] = 'No articles registered.' if @articles.empty?
  end

  def show
    @item = @items.find(params[:article_id])
    if user_signed_in? == false
      random_email = rand(36**30).to_s(36)
      @user = User.new(:email => random_email + '@non_registered_user.com', :password => 'password', :password_confirmation => 'password')
      @user.save
      sign_in @user
    end
    @product ||= Product.create(category_id: @item.category_id, article_id: @item.id, approved: false, sended: false)
  end



  def colour_personalization
    @product.update(user: current_user)
    gon.item = @item
    @image1 = @item.image1
    @parts_count = @item.parts_count
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = 'article registered successfully.'
      #redirect_to products_path
    else
      flash[:error] = @article.errors.full_messages.join(',')
      #render 'new'
    end
  end

  private

  def set_items
    @items = Article.where(category_id: params[:category_id])
  end
  def set_item
    @item = Article.find(params[:article_id])
  end
  def set_product
    @product = Product.find(params[:product_id])
  end

  def article_params
    params.require(:article).permit(:article_name, :description,
                                    :image1, :image2, :image3, :dimension)
  end
end

app/views/articles/_articles_slider.html.erb
  <div id="carousel-wrap">
    <ul id="carousel" class="top_slider roundabout-holder" style="margin-top: 200px;">
    <% @items.each do |item| %>
      <li>
        <span class="project-wrap"><span class="view-project-button">View Project</span></span>
          <%=link_to image_tag( asset_path(item.image1.to_s + ".jpg") , class: "slide", id: "slide"), article_description_path(params[:category_id], item.id) %>
      </li>
      <%end%>
    </ul>
  </div>

app/views/articles/articles_index.html.erb
<h1>Seleccione un articulo</h1>
<%= render partial: "articles_slider", locals: {items: @items}%>
<br />

app/views/articles/index.html.erb
<h4>Articles</h4>

<table class="table">
  <thead>
    <th>Id</th>
    <th>Article</th>
    <th>Description</th>
    <th>Image 1</th>
    <th>Image 2</th>
    <th>Image 3</th>
    <th>Dimension</th>
    <th>Available</th>
    <th>Category</th>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td> <%= article.id %> </td>
        <td><%= article.article_name %></td>
        <td><%= article.description %></td>
        <td> <%= article.image1 %> </td>
        <td> <%= article.image2 %> </td>
        <td> <%= article.image3 %> </td>
        <td> <%= article.dimension %> </td>
        <td> <%= article.available %> </td>
        <td> <%= article.category_id %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Página princial", root_path, class: 'btn btn-default' %>

app/views/articles/new.html.erb
<div class="row" >
  <div class="col-md-3"></div>
  <div class="col-md-6"> <h3> New Category </h3> </div>
  <div class="col-md-3"></div>
</div>

<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for @article, url: {action: 'create'} do |art|%>
      <div class="row">
        <div class="col-md-6"> <%= art.label :article_name, for:'article_name'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= art.text_field :article_name, class:'form-control' %> </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6"> <%= art.label :description, for:'description'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= art.text_field :description, class:'form-control' %> </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6"> <%= art.label :image1, for:'image1'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= art.text_field :image1, class:'form-control' %> </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6"> <%= art.label :image2, for:'image2'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= art.text_field :image2, class:'form-control' %> </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6"> <%= art.label :image3, for:'image3'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= art.text_field :image3, class:'form-control' %> </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6"> <%= art.label :dimension, for:'dimension'%> </div>
        <div class="col-md-6">
          <div class="form-group"> <%= art.text_field :dimension, class:'form-control' %> </div>
        </div>
      </div>

      <div class="form-group">
        <%= art.submit "Create article", class: 'btn btn-success'%>
      </div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

<%= link_to "Página princial", root_path, class: 'btn btn-default' %>

app/views/articles/show.html.erb
<div class="container">
		<div class="articles-slider col-lg-12 col-md-12 col-s-12" id="article-desc">
			<%= render partial: "articles_slider", locals: {items: @items}%>
		</div>
		<div class="articles-desc col-lg-10 col-md-10 col-s-12" id="articles-desc">
			<div class="articles-desc--img col-lg-5 col-md-5 col-s-10">
				<%=image_tag( asset_path(@item.image1.to_s + ".jpg"), size:"300x300")%>
			</div>
			<div class="articles-desc--text col-lg-7 col-md-7 col-s-10">
				<h1><%= @item.article_name %></h1></br>
				<h3><%= @item.dimension %></h3></br>
				<%= @item.description %></br>
				<%= @item.dimension %></br>
			</div>
		</div>
</div>

<div class="articles-desc col-lg-12 col-md-10 col-s-12">
	<%= link_to 'Next <i class="fa fa-caret-right" aria-hidden="true"></i> '.html_safe, article_color_personalization_path(user_id: current_user.id, product_id:@product.id), class: 'next-btn' %>
</div>