config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'category#select'
  get '/categories/:category_id', to: 'articles#articles_index', as: 'category_articles'
  get '/categories/:category_id/articles/:article_id', to: 'articles#show', as: 'article_description'
  get '/users/:user_id/products', to: 'products#user_products_index', as: 'user_products'
  get '/users/:user_id/products/user_data_registry', to: 'products#user_data_registry', as: 'user_data_registry'
  get '/categories/:category_id/articles/:article_id/users/:user_id/products/:product_id/parts/colour_personalization', to: 'articles#colour_personalization', as: 'article_color_personalization'
  post'/material_parts', to: 'material_parts#create'
  # get '/articles/new', to: 'articles#create', as: 'new_article'
  resources :articles, only: [:index, :new, :create, :update, :destroy]
  resources :category
  resources :manufacturer
  resources :products do
    resources :category
    resources :manufacturer
  end
  resources :users do
    resources :products
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :manufacturer
  belongs_to :category
  belongs_to :article
  has_many :material_parts
  has_many :parts
  has_many :parts, through: :material_parts
  scope :by_id, -> (id) { where("id = ?", "#{id}") }
  scope :by_user, -> (user_id) { where("user_id = ?", "#{user_id}") }
end

app/controllers/products_controller.rb
#:nodoc:
class ProductsController < ApplicationController

  before_action :set_products, only: [:user_products_index, :user_data_registry, :delete_non_personalized_products, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def user_products_index
    build_product_colors_array
  end

  def user_data_registry
    build_product_colors_array
  end

  def initialize_product_colors_array
    @product_colors = Array.new
    delete_non_personalized_products
    @products.each do
      @product_colors << []
    end
  end

  def build_product_colors_array
    initialize_product_colors_array
    @products.each_with_index do |product, index|
      @product_colors[index] << product.material_parts.map(&:material).map(&:color)
    end
    gon.product_colors = @product_colors
  end

  def delete_non_personalized_products
    @products.each do |product|
      product.destroy unless product.material_parts.map(&:material).map(&:color).present?
    end
  end

  def destroy
    product = Product.by_id(params[:id]).by_user(current_user.id).first
    product.destroy
    redirect_to user_products_path
  end

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  # def create
  #   @product = Product.new(product_params)
  #   if @product.save
  #     flash[:success] = 'product registered successfully.'
  #     redirect_to products_path
  #   else
  #     flash[:error] = @product.errors.full_messages.join(',')
  #     render 'new'
  #   end
  # end

  def create
    @product = Product.new(product_params)
    @product.save
    render nothing: true
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      render 'Edit'
    end
  end

  def product_params
    params.permit(:category_id, :manufacturer_id, :approved, :sended, :price, :article_id, :user_id)
  end
  private :product_params

  def set_products
    @products = current_user.products.includes(:material_parts)
  end
end

app/views/products/cart_form.html.erb
<h3 class= "title">Confirm Purchase</h3>
	<h3 class="subtitle">This is your creation   <i class="fa fa-heart" aria-hidden="true"></i></h3>
	<div class="cart-form col-lg-12 col-md-12 col-s-12">
		<table class="table cart-form--table">
		  <thead>
		    <tr>
		      <th>PRODUCT</th>
		      <th>COLORS</th>
		      <th>FABRIC INTERIOR</th>
		      <th>FABRIC EXTERIOR</th>
		      <th>PRICE</th>
		    </tr>
		  </thead>
		  <tbody>
		      <tr>
		        <td><%= image_tag("bag-demo.jpg", :class => "cart-form--img")%></td>
		        <td>
		        <center><span class="color-box box-one"></span>
		        <span class="color-box box-two"></span>
		        <span class="color-box box-three"></span>
		        <span class="color-box box-four"></span>
		        <span class="color-box box-five"></span></center></td>
		        <td><center>-</center></td>
		        <td><center>-</center></td>
		        <td><div class="price"><center>$200</center></div></td>
		      </tr>
		  </tbody>
		</table>
	</div>
<div class="cart-form col-lg-12 col-md-12 col-small-12">
	<h3 class="subtitle">Let's buy   <i class="fa fa-shopping-cart" aria-hidden="true"></i></h3>
</div>
<div class="cart-form col-lg-12 col-md-12 col-small-12">
	<h3 class="subtitle">Tell us about you to send your product   <i class="fa fa-shopping-cart" aria-hidden="true"></i></h3>
	<form class="form-horizontal" id="form-purchase" action="">
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">Your mame</label>
			<div class="col-sm-9">
			  <input type="text" class="form-control" id="username" onblur="validate()">
		</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">Your Last Name</label>
			<div class="col-sm-9">
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">E-mail</label>
			<div class="col-sm-9">
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">Address</label>
			<div class="col-sm-9">
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="cart-form--btn">
			<center>
			  <button type="submit" id="login" class="btn btn-success">Buy</button>
			  <button class="btn btn-danger" type="reset">Cancel</button>
			</center>
		</div>
		<div class="row">
			<div class="pull-right col-sm-12 col-md-8 col-lg-8">
				<p id="error"></p>
			</div>
		</div>
		<div class="row">
		</div>
	</form>
</div>
</div>
	
</div>

app/views/products/cart_resume.html.erb
<h2 class="title">Checking if we got it right!</h2>
<h3 class= "subtitle">This is what you chose:</h3>


<div class="cart-block col-lg-12 col-md-12 col-s-12">
	<table class="table cart-block--table">
	  <thead>
	    <tr>
	      <th>PRODUCT</th>
	      <th>COLORS</th>
	      <th>FABRIC INTERIOR</th>
	      <th>FABRIC EXTERIOR</th>
	    </tr>
	  </thead>
	  <tbody>
	      <tr>
	        <td><%= image_tag("bag-demo.jpg", :class => "cart-block--img")%></td>
	        <td>
	        <center><span class="color-box box-one"></span>
	        <span class="color-box box-two"></span>
	        <span class="color-box box-three"></span>
	        <span class="color-box box-four"></span>
	        <span class="color-box box-five"></span></center></td>
	        <td><center>-</center></td>
	        <td><center>-</center></td>
	      </tr>
	  </tbody>
	</table>
	<div class="col-lg-12 col-md-12 col-s-12">
		<div class="cartmenu">
		  <div class="cartmenu-item"><a href="#" class="cartmenu-item--link">Quantity: select</a></div>
		  <div class="cartmenu-item">
		  	<%= link_to '<i class="fa fa-times" aria-hidden="true"></i> Eliminate'.html_safe, root_path, class: 'cartmenu-item--link cartmenu-item--delete' %>
		  </div>
		  <div class="cartmenu-item">
		  	<%= link_to '<i class="fa fa-caret-left" aria-hidden="true"></i> Go back and edit'.html_safe, root_path, class: 'cartmenu-item--link cartmenu-item--edit' %>
			</div>
		</div>
	</div>
</div>

<div class="cart-block recycled col-lg-12 col-md-12 col-s-12">
	<div class="col-lg-5 col-md-5 col-s-12"><%= image_tag("recycled-text.png", :class => "recycled--img")%></div>
	<div class="col-lg-7 col-md-7 col-s-12">
		<div class="recycled-result col-lg-3 col-md-3 col-s-12">
			<span class="recycled-result--num">
				7.5
			</span>
			<span class="recycled-result--desc">
				Kilos
			</span>
		</div>
		<div class="recycled-result col-lg-3 col-md-3 col-s-12">
			<span class="recycled-result--num">
				16.5
			</span>
			<span class="recycled-result--desc">
				Pounds
			</span>
		</div>
	</div>
</div>

<div class="cart-block manufacture col-lg-12 col-md-12 col-s-12">
	<h2 class="manufacture-title">Chose WHO will <span class="manufacture-title--img"></span> your piece</h2>
	<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">
	<span class="arrow"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
	</button>
	 <div id="demo" class="collapse col-lg-12 col-md-12 col-s-12">
	 	<div class="mother col-lg-4 col-md-4 col-s-12">
	 		<div class="mother-img"><%= image_tag("madres/mom1.jpg", :class => "mother-img--img")%></div>
	 		<div class="mother-desc">
	 			<h2>Eliana Vélez</h2>
	 			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam nisi viverra ligula sodales gravida. Aenean et mattis neque, eget interdum turpis. Etiam tristique augue dolor, non interdum lacus sollicitudin condimentum. Aliquam consequat lobortis sapien in semper. Sed nec rutrum quam. Fusce non mi est. In tincidunt nisl eu nisi blandit, faucibus iaculis felis semper. Nunc aliquet orci id risus suscipit accumsan. Aenean vehicula, dolor ac hendrerit sollicitudin, orci orci commodo dui, et volutpat arcu leo at lacus.
	 			<%= link_to 'Select'.html_safe, root_path, class: 'mother-link' %>

	 		</div>
	 	</div>
	 	<div class="mother col-lg-4 col-md-4 col-s-12">
	 		<div class="mother-img"><%= image_tag("madres/mom2.jpg", :class => "mother-img--img")%></div>
	 		<div class="mother-desc">
	 			<h2>Angela Castillo</h2>
	 			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam nisi viverra ligula sodales gravida. Aenean et mattis neque, eget interdum turpis. Etiam tristique augue dolor, non interdum lacus sollicitudin condimentum. Aliquam consequat lobortis sapien in semper. Sed nec rutrum quam. Fusce non mi est. In tincidunt nisl eu nisi blandit, faucibus iaculis felis semper. Nunc aliquet orci id risus suscipit accumsan. Aenean vehicula, dolor ac hendrerit sollicitudin, orci orci commodo dui, et volutpat arcu leo at lacus.
	 			<%= link_to 'Select'.html_safe, root_path, class: 'mother-link' %>
	 		</div>
	 	</div>
	 	<div class="mother col-lg-4 col-md-4 col-s-12">
	 		<div class="mother-img"><%= image_tag("madres/mom3.jpg", :class => "mother-img--img")%></div>
	 		<div class="mother-desc">
	 			<h2>Viviana Ocampo</h2>
	 			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam nisi viverra ligula sodales gravida. Aenean et mattis neque, eget interdum turpis. Etiam tristique augue dolor, non interdum lacus sollicitudin condimentum. Aliquam consequat lobortis sapien in semper. Sed nec rutrum quam. Fusce non mi est. In tincidunt nisl eu nisi blandit, faucibus iaculis felis semper. Nunc aliquet orci id risus suscipit accumsan. Aenean vehicula, dolor ac hendrerit sollicitudin, orci orci commodo dui, et volutpat arcu leo at lacus.
	 			<%= link_to 'Select'.html_safe, root_path, class: 'mother-link' %>
	 		</div>
	 	</div>

	  </div>	
</div>
<div class="quote col-lg-12 col-md-12 col-small-12">
	<p>Choose for <span class="quote-img"></span> <i class="fa fa-heart" aria-hidden="true"></i> </p>
</div>
<div class="col-lg-12 col-md-12 col-s-12">
	<div class="btn-nav">
		<%= link_to '<i class="fa fa-caret-left" aria-hidden="true"></i> Continue Shopping '.html_safe, root_path, class: 'btn-nav--left' %>
		<%= link_to 'Go to Check Out <i class="fa fa-caret-right" aria-hidden="true"></i> '.html_safe, root_path, class: 'btn-nav--right' %>
	</div>
</div>
</div>
	
</div>

app/views/products/index.html.erb
<h4>Products</h4>

<table class="table">

  <thead>
    <tr>
      <th>Comprador</th>
      <th>Fabricante</th>
      <th>Categoría</th>
      <th>Referencia</th>
      <th>Aprobado</th>
      <th>Enviado</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |m| %>
      <tr>
        <td><%= m.user_id %></td>
        <td><%= m.manufacturer_id %></td>
        <td><%= m.category.category_name%></td>
        <td><%= m.article.article_name %></td>
        <td><%= m.approved %></td>
        <td><%= m.sended %></td>
        <td><%= m.price %></td>
      </tr>
    <% end %>
  </tbody>

</table>



<%= link_to "Inicio", root_path %>

app/views/products/index1.html.erb
<h4>Products</h4>

<table class="table">

  <thead>
    <tr>
      <th>Fabricante</th>
      <th>Categoría</th>
      <th>Referencia</th>
      <th>Aprobado</th>
      <th>Enviado</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |m| %>
      <tr>
        <td><%= m.manufacturer_id %></td>
        <td><%= m.category_id %></td>
        <td><%= m.article_id %></td>
        <td><%= m.approved %></td>
        <td><%= m.sended %></td>
        <td><%= m.price %></td>
      </tr>
    <% end %>
  </tbody>

</table>



<%= link_to "Inicio", root_path %>

app/views/products/new.html.erb
<div class="row text-center">
  <div class="row">
    <h2>Nuevo Producto</h2>
  </div>
<ul>
     <% Category.all.each do |category| %>
    <li><%= link_to category.category_name, products_path(category: category.category_name) %></li>
    <% end %>
</ul>

</div>

app/views/products/show.html.erb
<div class="row text-center">
  <div class="row">
    <h2>Personalizar</h2>
  </div>

  <div class="row">
    <div class="col-md-4"> <%= link_to "Bolsos", product_path %> </div>
    <div class="col-md-4"> <%= link_to "Pañoleta", product_path %> </div>
    <div class="col-md-4"> <%= link_to "Tapetes", product_path %> </div>
  </div>
  <br />
  <br />
</div>
<%= link_to "Inicio", root_path %>

app/views/products/user_data_registry.html.erb
<h3 class="title">Confirm Purchase</h3>
<h3 class="subtitle">This is your creation
	<i class="fa fa-heart" aria-hidden="true"></i>
</h3>
<%= include_gon %>
<div class="cart-form col-lg-12 col-md-12 col-s-12">
	<table class="table cart-form--table">
		<thead>
			<tr>
				<th>PRODUCT</th>
				<th>COLORS</th>
				<th>FABRIC INTERIOR</th>
				<th>FABRIC EXTERIOR</th>
				<th>PRICE</th>
			</tr>
		</thead>
		<tbody>
			<script>
			var index = 0;
			</script>
			<%@products.each do |prod|%>
			<tr>
				<td><%= image_tag(asset_path(prod.article.image1.to_s + ".jpg"), :class => "cart-block--img")%></td>
				<td>
					<center>
						<script>
							var id_one = Math.random().toString(36).substring(7);
							var id_two = Math.random().toString(36).substring(7);
							var id_three = Math.random().toString(36).substring(7);
							var id_four = Math.random().toString(36).substring(7);
							var id_five = Math.random().toString(36).substring(7);
							document.write('<span id='.concat(id_one).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_two).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_three).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_four).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_five).concat(' class="color-box"> </span>'));

							var product_colors = gon.product_colors
							document.getElementById(id_one).style.backgroundColor = product_colors[index][0][0];
							document.getElementById(id_two).style.backgroundColor = product_colors[index][0][1];
							document.getElementById(id_three).style.backgroundColor = product_colors[index][0][2];
							document.getElementById(id_four).style.backgroundColor = product_colors[index][0][3];
							document.getElementById(id_five).style.backgroundColor = product_colors[index][0][4];
							if (typeof product_colors[index][0][0] === 'undefined' || product_colors[index][0][0] === null) {
								alert(' Aplicación en construcción, si desea observar el listado de colores elegidos  seleccione el primer producto de la categoría bags')
							}
							index += 1;
						</script>
					</center>
				</td>
				<td>
					<center><%=prod.material_parts.first.material.material_name if prod.material_parts.first.present?%></center>
				</td>
				<td>
					<center><%=prod.material_parts.first(2).last.material.material_name if prod.material_parts.first.present?%></center>
				</td>
			</tr>
			<%end%>
		</tbody>
	</table>
</div>
<div class="cart-form col-lg-12 col-md-12 col-small-12">
	<h3 class="subtitle">Let's buy
		<i class="fa fa-credit-card-alt" aria-hidden="true"></i>
	</h3>
</div>
<div class="cart-form col-lg-12 col-md-12 col-small-12">
	<h3 class="subtitle">Tell us about you to send your product
		<i class="fa fa-shopping-cart" aria-hidden="true"></i>
	</h3>
	<form class="form-horizontal" id="form-purchase" action="">
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">Your mame</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" id="username" onblur="validate()">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">Your Last Name</label>
			<div class="col-sm-9">
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">E-mail</label>
			<div class="col-sm-9">
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" for="Username">Address</label>
			<div class="col-sm-9">
				<input type="text" class="form-control">
			</div>
		</div>
		<div class="cart-form--btn">
			<center>
				<button type="submit" id="login" class="btn btn-buy">Buy</button>
				<button class=" btn btn-cancel" type="reset">Cancel</button>
			</center>
		</div>
		<div class="row">
			<div class="pull-right col-sm-12 col-md-8 col-lg-8">
				<p id="error"></p>
			</div>
		</div>
		<div class="row"></div>
	</form>
</div>
</div>

</div>

app/views/products/user_products_index.html.erb
<h2 class="title">Checking if we got it right!</h2>
<h3 class="subtitle">This is what you chose:</h3>
<%= include_gon %>

<table class="table cart-block--table">
	<thead>
		<tr>
			<th>PRODUCT</th>
			<th>COLORS</th>
			<th>FABRIC INTERIOR</th>
			<th>FABRIC EXTERIOR</th>
		</tr>
	</thead>
	<div class="cart-block col-lg-12 col-md-12 col-s-12">
		<tbody>
			<script>
				var index = gon.product_colors.length - 1 ;
			</script>
			<%@products.reverse_each do |prod|%>

			<tr>
				<td>
					<%= image_tag(asset_path(prod.article.image1.to_s + ".jpg"), :class => "cart-block--img")%>
				</td>
				<td>
					<center>
						<script>
							var product_colors = gon.product_colors
							var id_one = Math.random().toString(36).substring(7);
							var id_two = Math.random().toString(36).substring(7);
							var id_three = Math.random().toString(36).substring(7);
							var id_four = Math.random().toString(36).substring(7);
							var id_five = Math.random().toString(36).substring(7);

							document.write('<span id='.concat(id_one).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_two).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_three).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_four).concat(' class="color-box"> </span>'));
							document.write('<span id='.concat(id_five).concat(' class="color-box"> </span>'));

							document.getElementById(id_one).style.backgroundColor = product_colors[index][0][0];
							document.getElementById(id_two).style.backgroundColor = product_colors[index][0][1];
							document.getElementById(id_three).style.backgroundColor = product_colors[index][0][2];
							document.getElementById(id_four).style.backgroundColor = product_colors[index][0][3];
							document.getElementById(id_five).style.backgroundColor = product_colors[index][0][4];
							index -= 1;
						</script>
					</center>
				</td>
				<td>
					<center><%=prod.material_parts.first.material.material_name if prod.material_parts.first.present?%></center>
				</td>
				<td>
					<center><%=prod.material_parts.first(2).last.material.material_name if prod.material_parts.first.present?%></center>
				</td>
			</tr>


			<tr>
				<td colspan="4" style="height:15px;">
					<div class="col-lg-12 col-md-12 col-s-12">
						<div class="cartmenu">
							<div class="cartmenu-item">
								<a href="#" class="cartmenu-item--link">Quantity: select</a>
							</div>
							<div class="cartmenu-item">
								<%= link_to '<i class="fa fa-times" aria-hidden="true"></i> Eliminate'.html_safe, user_product_path(current_user, prod),
                        method: 'delete',
                        class: 'btn btn-danger',
                        data: {confirm: "Are you sure?"}, class: 'cartmenu-item--link cartmenu-item--delete' %>
							</div>
							<div class="cartmenu-item">
								<%= link_to '<i class="fa fa-caret-left" aria-hidden="true"></i> Go back and edit'.html_safe, root_path, class: 'cartmenu-item--link cartmenu-item--edit' %>
							</div>
						</div>
					</div>
				</td>
			</tr>

			<%end%>
		</tbody>
	</div>
</table>

<div class="cart-block recycled col-lg-12 col-md-12 col-s-12">
	<div class="col-lg-5 col-md-5 col-s-12"><%= image_tag("recycled-text.png", :class => "recycled--img")%></div>
	<div class="col-lg-7 col-md-7 col-s-12">
		<div class="recycled-result col-lg-3 col-md-3 col-s-12">
			<span class="recycled-result--num">
				7.5
			</span>
			<span class="recycled-result--desc">
				Kilos
			</span>
		</div>
		<div class="recycled-result col-lg-3 col-md-3 col-s-12">
			<span class="recycled-result--num">
				16.5
			</span>
			<span class="recycled-result--desc">
				Pounds
			</span>
		</div>
	</div>
</div>

<div class="cart-block manufacture col-lg-12 col-md-12 col-s-12">
	<h2 class="manufacture-title">Chose WHO will
		<span class="manufacture-title--img"></span>
		your piece</h2>
	<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">
		<span class="arrow">
			<i class="fa fa-caret-down" aria-hidden="true"></i>
		</span>
	</button>
	<div id="demo" class="collapse col-lg-12 col-md-12 col-s-12">
		<div class="mother col-lg-4 col-md-4 col-s-12">
			<div class="mother-img"><%= image_tag("madres/mom1.jpg", :class => "mother-img--img")%></div>
			<div class="mother-desc">
				<h2>Eliana Vélez</h2>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam nisi viverra ligula sodales gravida. Aenean et mattis neque, eget interdum turpis. Etiam tristique augue dolor, non interdum lacus sollicitudin condimentum. Aliquam consequat
				lobortis sapien in semper. Sed nec rutrum quam. Fusce non mi est. In tincidunt nisl eu nisi blandit, faucibus iaculis felis semper. Nunc aliquet orci id risus suscipit accumsan. Aenean vehicula, dolor ac hendrerit sollicitudin, orci orci commodo dui,
				et volutpat arcu leo at lacus.
				<%= link_to 'Select'.html_safe, root_path, class: 'mother-link' %>

			</div>
		</div>
		<div class="mother col-lg-4 col-md-4 col-s-12">
			<div class="mother-img"><%= image_tag("madres/mom2.jpg", :class => "mother-img--img")%></div>
			<div class="mother-desc">
				<h2>Angela Castillo</h2>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam nisi viverra ligula sodales gravida. Aenean et mattis neque, eget interdum turpis. Etiam tristique augue dolor, non interdum lacus sollicitudin condimentum. Aliquam consequat
				lobortis sapien in semper. Sed nec rutrum quam. Fusce non mi est. In tincidunt nisl eu nisi blandit, faucibus iaculis felis semper. Nunc aliquet orci id risus suscipit accumsan. Aenean vehicula, dolor ac hendrerit sollicitudin, orci orci commodo dui,
				et volutpat arcu leo at lacus.
				<%= link_to 'Select'.html_safe, root_path, class: 'mother-link' %>
			</div>
		</div>
		<div class="mother col-lg-4 col-md-4 col-s-12">
			<div class="mother-img"><%= image_tag("madres/mom3.jpg", :class => "mother-img--img")%></div>
			<div class="mother-desc">
				<h2>Viviana Ocampo</h2>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam nisi viverra ligula sodales gravida. Aenean et mattis neque, eget interdum turpis. Etiam tristique augue dolor, non interdum lacus sollicitudin condimentum. Aliquam consequat
				lobortis sapien in semper. Sed nec rutrum quam. Fusce non mi est. In tincidunt nisl eu nisi blandit, faucibus iaculis felis semper. Nunc aliquet orci id risus suscipit accumsan. Aenean vehicula, dolor ac hendrerit sollicitudin, orci orci commodo dui,
				et volutpat arcu leo at lacus.
				<%= link_to 'Select'.html_safe, root_path, class: 'mother-link' %>
			</div>
		</div>

	</div>
</div>
<div class="quote col-lg-12 col-md-12 col-small-12">
	<p>Choose for
		<span class="quote-img"></span>
		<i class="fa fa-heart" aria-hidden="true"></i>
	</p>
</div>
<div class="col-lg-12 col-md-12 col-s-12">
	<div class="btn-nav">
		<%= link_to '<i class="fa fa-caret-left" aria-hidden="true"></i> Continue Shopping '.html_safe, root_path, class: 'btn-nav--left' %>
		<%= link_to 'Go to Check Out <i class="fa fa-caret-right" aria-hidden="true"></i> '.html_safe, user_data_registry_path(user_id: @products.first.user_id), class: 'btn-nav--right' %>
	</div>
</div>
</div>

</div>