config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'category#select'
  get '/categories/:category_id', to: 'articles#articles_index', as: 'category_articles'
  get '/categories/:category_id/articles/:article_id', to: 'articles#show', as: 'article_description'
  get '/users/:user_id/products', to: 'products#user_products_index', as: 'user_products'
  get '/users/:user_id/products/user_data_registry', to: 'products#user_data_registry', as: 'user_data_registry'
  get '/categories/:category_id/articles/:article_id/users/:user_id/products/:product_id/parts/colour_personalization', to: 'articles#colour_personalization', as: 'article_color_personalization'
  post'/material_parts', to: 'material_parts#create'
  # get '/articles/new', to: 'articles#create', as: 'new_article'
  resources :articles, only: [:index, :new, :create, :update, :destroy]
  resources :category
  resources :manufacturer
  resources :products do
    resources :category
    resources :manufacturer
  end
  resources :users do
    resources :products
  end


end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer col-lg-12">
  <div class="container">
    <div class="socials col-lg-12 col-md-12 col-s-12">
    <ul class="social">
      <li class="social-item"><a href="" class="social-item--link"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
      <li class="social-item"><a href="" class="social-item--link"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
      <li class="social-item"><a href="" class="social-item--link"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
      <li class="social-item"><a href="" class="social-item--link"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
    </ul>
    </div>
    <div class="legal col-lg-12 col-md-12 col-s-12">
     <p class="col-lg-12 col-md-12 col-s-12">
      Copyrights Anastasia Inc. All Rights Reserved 2016
     </p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header-slider">
      <div class="container">
        <%= link_to image_tag("header-img.jpg", :alt => "header-slider--img", :class => "header-slider--img"), root_path%>
      </div>
  </div>
  <div class="navbar navbar-default">
      <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="nav-item active"><%= link_to "Home", root_path, :class => "nav-item--link" %> <span class="sr-only">(current)</span></li>
          <li class="nav-item"><a class="nav-item--link" href="#">Bazaar</a></li>
          <li class="nav-item">
          <li class="nav-item"><a class="nav-item--link" href="#">Indie Anastasia</a></li>
          <li class="nav-item"><a class="nav-item--link" href="#">Press</a></li>
          <li class="nav-item"><a class="nav-item--link" href="#">Inspiring Spotlight</a></li>
          <li class="nav-item"><a class="nav-item--link" href="#">Contact Us</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </div>
</header>

app/views/layouts/_product_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Anastasia</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manufacturers <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Manufacturer", new_manufacturer_path %></li>
            <li><%= link_to "All manufacturer", manufacturer_index_path %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Management <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New category", new_category_path %></li>
            <li><%= link_to "All categories", category_index_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "New article", new_article_path %></li>
            <li><%= link_to "All articles", articles_path %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All porducts", products_path %></li>
          </ul>
        </li>
      </ul>

    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Anastasia</title>
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/product_menu", locals: { devise_login: true } %>
    <% #Menu Product navigation, evetually it will be show only on Admin view %>
    <%= render partial: "layouts/header" %>
    <div class="container">
      <%= render partial: "layouts/flash_messages", flash: flash %>
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
  <%= javascript_include_tag 'roundabout', 'data-turbolinks-track' => true %>
</html>